-- Seed de referencia para soporte interno.
-- Reemplazar IDs y datos segun el tenant/usuario real antes de ejecutar.
-- No contiene secretos fiscales ni API keys.

-- with tenant_base as (
--   insert into tenants (nombre, slug)
--   values ('Tenant Demo', 'tenant-demo')
--   on conflict (slug) do update set nombre = excluded.nombre
--   returning id
-- ),
-- plan_base as (
--   select id from planes where codigo = 'BASICO_MVP'
-- ),
-- suscripcion as (
--   insert into tenant_suscripciones (tenant_id, plan_id)
--   select tenant_base.id, plan_base.id from tenant_base, plan_base
--   on conflict do nothing
-- ),
-- facturador as (
--   insert into facturadores (tenant_id, emisor_id, razon_social, ruc)
--   select id, '80136968-1', 'Facturador Demo', '80136968-1' from tenant_base
--   returning id, tenant_id
-- ),
-- establecimiento as (
--   insert into facturador_establecimientos (tenant_id, facturador_id, codigo, nombre)
--   select tenant_id, id, '001', 'Casa matriz' from facturador
--   returning id, tenant_id, facturador_id
-- ),
-- punto as (
--   insert into facturador_puntos_expedicion (tenant_id, facturador_id, establecimiento_id, codigo, nombre)
--   select tenant_id, facturador_id, id, '001', 'Punto 001' from establecimiento
--   returning id, tenant_id, facturador_id, establecimiento_id
-- ),
-- actividad as (
--   insert into facturador_actividades (tenant_id, facturador_id, codigo, descripcion)
--   select tenant_id, facturador_id, '82110', 'Servicios administrativos' from facturador
--   returning id, tenant_id, facturador_id
-- ),
-- perfil as (
--   insert into facturador_perfiles_emision (tenant_id, facturador_id, codigo, descripcion)
--   select tenant_id, facturador_id, 'SERV', 'Servicios' from facturador
--   returning id, tenant_id, facturador_id
-- )
-- insert into actividad_punto_perfiles (
--   tenant_id,
--   facturador_id,
--   actividad_id,
--   establecimiento_id,
--   punto_expedicion_id,
--   perfil_emision_id,
--   timbrado,
--   timbrado_inicio,
--   documento_nro,
--   credito_plazo_dias
-- )
-- select
--   actividad.tenant_id,
--   actividad.facturador_id,
--   actividad.id,
--   punto.establecimiento_id,
--   punto.id,
--   perfil.id,
--   '80136968',
--   date '2025-12-30',
--   '0000000',
--   30
-- from actividad, punto, perfil;

-- Cliente de referencia para validaciones manuales de compra de servicios:
--
-- with identidad_cliente as (
--   insert into cliente_identidades (
--     documento_tipo,
--     documento,
--     documento_normalizado,
--     razon_social
--   )
--   values ('RUC', '492019-8', '4920198', 'Roberto Saldivar')
--   on conflict (documento_tipo, documento_normalizado)
--   where deleted_at is null
--   do update set
--     documento = excluded.documento,
--     razon_social = excluded.razon_social
--   returning id
-- )
-- insert into facturador_clientes (
--   tenant_id,
--   facturador_id,
--   cliente_identidad_id,
--   razon_social
-- )
-- select
--   f.tenant_id,
--   f.id,
--   identidad_cliente.id,
--   'Roberto Saldivar'
-- from facturadores f, identidad_cliente
-- where f.ruc = '80136968-1'
-- on conflict (facturador_id, cliente_identidad_id)
-- where deleted_at is null
-- do update set razon_social = excluded.razon_social;
