import { describe, expect, it } from "vitest";
import {
  createCatalogoItem,
  listCatalogoItems,
  normalizeCatalogoInput,
  searchCatalogoItems,
  updateCatalogoItem
} from "../src/modules/catalogo/catalogo.service";
import type {
  CatalogoItem,
  CatalogoItemListResponse,
  CatalogoItemPersistInput,
  CatalogoItemUpsertInput,
  CatalogoRepository
} from "../src/modules/catalogo/catalogo.types";
import type { OperationalContextResponse } from "../src/modules/context/context.types";

const context: OperationalContextResponse = {
  user: {
    id: "11111111-1111-4111-8111-111111111111",
    username: "operador",
    display_name: "Operador",
    role: "OPERADOR_FACTURACION"
  },
  tenant: {
    id: "22222222-2222-4222-8222-222222222222",
    name: "Tenant Demo",
    status: "ACTIVE"
  },
  facturador: {
    id: "33333333-3333-4333-8333-333333333333",
    emisor_id: "80136968-1",
    razon_social: "Facturador Demo",
    ruc: "80136968-1"
  },
  fiscal_context: {
    establecimiento: "001",
    punto_expedicion: "001",
    perfil_emision_codigo: "SERV",
    actividad_economica_codigo: "82110",
    actividad_economica_descripcion: "Servicios administrativos",
    timbrado: "80136968",
    timbrado_inicio: "2025-12-30",
    documento_nro: "0000000",
    credito_plazo_dias: 30
  }
};

const item: CatalogoItem = {
  id: "44444444-4444-4444-8444-444444444444",
  codigo: "SERV-001",
  descripcion: "Servicio profesional",
  precio_unitario: 100000,
  iva_tipo: "IVA_10",
  activo: true
};

class FakeCatalogoRepository implements CatalogoRepository {
  public existingCodes = new Set<string>();
  public lastSearchInput: unknown;
  public lastListInput: unknown;
  public lastCreateInput: unknown;
  public lastUpdateInput: unknown;
  public updateResult: CatalogoItem | null = item;

  async search(input: { facturadorId: string; q: string; limit: number }): Promise<CatalogoItem[]> {
    this.lastSearchInput = input;
    return [item];
  }

  async list(input: { facturadorId: string; q?: string; activo?: boolean; limit: number; offset: number }): Promise<CatalogoItemListResponse> {
    this.lastListInput = input;
    return { items: [item], total: 1 };
  }

  async create(input: {
    tenantId: string;
    facturadorId: string;
    userId: string;
    data: CatalogoItemPersistInput;
  }): Promise<CatalogoItem> {
    this.lastCreateInput = input;
    return {
      id: item.id,
      codigo: input.data.codigo,
      descripcion: input.data.descripcion,
      precio_unitario: input.data.precio_unitario,
      iva_tipo: input.data.iva_tipo,
      activo: input.data.activo
    };
  }

  async update(input: {
    itemId: string;
    facturadorId: string;
    userId: string;
    data: CatalogoItemPersistInput;
  }): Promise<CatalogoItem | null> {
    this.lastUpdateInput = input;
    return this.updateResult;
  }

  async existsByCodigo(input: { codigoNormalizado: string }): Promise<boolean> {
    return this.existingCodes.has(input.codigoNormalizado);
  }
}

describe("catalogo service", () => {
  it("creates quick item with autogenerated code and IVA_10 by default", async () => {
    const repo = new FakeCatalogoRepository();

    const result = await createCatalogoItem(
      context,
      {
        descripcion: " Servicio nuevo ",
        precio_unitario: 50000
      },
      repo
    );

    expect(result.codigo).toMatch(/^AUTO-[A-F0-9]{8}$/);
    expect(result.iva_tipo).toBe("IVA_10");
    expect(repo.lastCreateInput).toMatchObject({
      tenantId: context.tenant.id,
      facturadorId: context.facturador.id,
      userId: context.user.id,
      data: {
        descripcion: "Servicio nuevo",
        precio_unitario: 50000,
        iva_tipo: "IVA_10",
        activo: true
      }
    });
  });

  it("rejects duplicated user-provided code", async () => {
    const repo = new FakeCatalogoRepository();
    repo.existingCodes.add("SERV-001");

    await expect(
      normalizeCatalogoInput(
        context.facturador.id,
        {
          codigo: " SERV-001 ",
          descripcion: "Servicio",
          precio_unitario: 1000
        },
        repo
      )
    ).rejects.toMatchObject({
      statusCode: 409
    });
  });

  it("searches by facturador context", async () => {
    const repo = new FakeCatalogoRepository();

    const result = await searchCatalogoItems(context, { q: "serv", limit: 10 }, repo);

    expect(result.items).toHaveLength(1);
    expect(repo.lastSearchInput).toEqual({
      facturadorId: context.facturador.id,
      q: "serv",
      limit: 10
    });
  });

  it("lists catalog by facturador context", async () => {
    const repo = new FakeCatalogoRepository();

    const result = await listCatalogoItems(context, { limit: 20, offset: 0, activo: true }, repo);

    expect(result.total).toBe(1);
    expect(repo.lastListInput).toEqual({
      facturadorId: context.facturador.id,
      q: undefined,
      activo: true,
      limit: 20,
      offset: 0
    });
  });

  it("throws not found when updating item outside facturador catalog", async () => {
    const repo = new FakeCatalogoRepository();
    repo.updateResult = null;

    await expect(
      updateCatalogoItem(
        context,
        item.id,
        {
          codigo: "SERV-002",
          descripcion: "Servicio",
          precio_unitario: 2000,
          iva_tipo: "IVA_5"
        },
        repo
      )
    ).rejects.toMatchObject({
      statusCode: 404
    });
  });

  it("rejects decimal prices", async () => {
    const repo = new FakeCatalogoRepository();

    await expect(
      normalizeCatalogoInput(
        context.facturador.id,
        {
          codigo: "SERV-003",
          descripcion: "Servicio",
          precio_unitario: 10.5
        },
        repo
      )
    ).rejects.toMatchObject({
      statusCode: 400
    });
  });
});
