server {
  listen 80;
  server_name _;

  location /api/v1/ {
    proxy_pass http://api:8080/api/v1/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /public/ {
    proxy_pass http://api:8080/public/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location = /backoffice {
    return 302 $scheme://$http_host/backoffice/;
  }

  location /backoffice/ {
    alias /usr/share/nginx/html/backoffice/;
    try_files $uri $uri/ /backoffice/index.html;
  }

  location = /app {
    return 302 $scheme://$http_host/app/;
  }

  location /app/ {
    alias /usr/share/nginx/html/app/;
    try_files $uri $uri/ /app/index.html;
  }

  location = / {
    return 302 $scheme://$http_host/app/;
  }
}
